version: "3.9"

services:
  api:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  app:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
